[package]
name = "linkerd2-opencensus"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2"
http-body = "0.4"
linkerd2-error = { path = "../error" }
linkerd2-metrics = { path = "../metrics" }
opencensus-proto = { path = "../../opencensus-proto" }
tonic = { version = "0.3", default-features = false, features = ["prost", "codegen"] }
tower = { version = "0.4", default-features = false }
tokio = { version = "0.3", features = ["macros", "sync", "stream"] }
tracing = "0.1.22"
